version: "3.7"

services:
    node_lts:
        build: "node/"
        container_name: "node"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=development
        volumes:
            - ./workspace:/home/node/app
        ports:
            - "4200:4200"
        networks:
            - app-network
        tty: true

    mysql_latest:
        build: "mysql/"
        container_name: "mysql"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_DATABASE: "homestead"
            MYSQL_ROOT_PASSWORD: secreate
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secreate
        volumes:
            - ./mysql/db-data:/var/lib/mysql
        ports:
            - "3306:3306"
            - "33060:33060"
        networks:
            - app-network
        tty: true

networks:
    app-network:
        driver: bridge
