version: "3.7"

services:
    php72:
        build: "php/"
        container_name: "php"
        user: "www-data"
        restart: always
        working_dir: /var/www/html
        volumes:
            - ./php/conf.d:/usr/local/etc/php/conf.d
            - ~/workspace:/var/www/html
        depends_on:
            - mysql_latest
        ports:
            - "9000:9000"
        networks:
            - app-network
        tty: true

    nginx_stable:
        build: "nginx/"
        container_name: "nginx"
        restart: always
        volumes:
            - ~/workspace:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - php72
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
        tty: true

    node_lts:
        build: "node/"
        container_name: "node"
        restart: always
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=development
        volumes:
            - ~/workspace:/home/node/app
        ports:
            - "4200:4200"
            - "3000:3000"
            - "8080:8080"
        networks:
            - app-network
        tty: true

    mysql_latest:
        build: "mysql/"
        container_name: "mysql"
        command: --default-authentication-plugin=mysql_native_password
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        restart: always
        environment:
            MYSQL_DATABASE: "homestead"
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_USER: "homestead"
            MYSQL_PASSWORD: "secret"
            SERVICE_NAME: mysql
            SERVICE_TAGS: dev
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3306:3306"
            - "33060:33060"
        networks:
            - app-network
        tty: true

networks:
    app-network:
        driver: bridge

volumes:
    db-data:
